2021-08-28 04:33:43 info: ---------------------------------------
2021-08-28 04:33:43 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-28 04:33:43 info: ---------------------------------------
2021-08-28 04:33:51 info: All unit tests passed.
2021-08-28 04:33:53 error: *** ESLint Report ***

ex1-johnWho.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-28 08:22:46 info: -------------------------------------------------
2021-08-28 08:22:46 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-28 08:22:46 info: -------------------------------------------------
2021-08-28 08:22:52 error: *** Unit Test Error Report ***

  console.log
    This is a double digit number!

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:25:30

  console.log
    Expected a double digit number but got 5

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:30:29

  console.log
    Expected a double digit number but got 123

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:34:29


2021-08-28 08:38:53 info: ----------------------------------------
2021-08-28 08:38:53 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-28 08:38:53 info: ----------------------------------------
2021-08-28 08:38:58 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollDice.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js
  rollDice
    × should call `new Promise()` (4 ms)
    × `resolve()` should be called with a one argument (3 ms)
    × `reject()` should be called with a one argument
    × should resolve when the dice settles successfully (11 ms)
    × should reject with an Error when the dice rolls off the table (1 ms)

  ● rollDice › should call `new Promise()`

    expect(received).toBeDefined()

    Received: undefined

      31 | 
      32 |   test('should call `new Promise()`', () => {
    > 33 |     expect(state.newPromise).toBeDefined();
         |                              ^
      34 |   });
      35 | 
      36 |   test('`resolve()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:33:30)

  ● rollDice › `resolve()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      35 | 
      36 |   test('`resolve()` should be called with a one argument', () => {
    > 37 |     expect(state.resolve).toBe(1);
         |                           ^
      38 |   });
      39 | 
      40 |   test('`reject()` should be called with a one argument', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:37:27)

  ● rollDice › `reject()` should be called with a one argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: undefined

      39 | 
      40 |   test('`reject()` should be called with a one argument', () => {
    > 41 |     expect(state.reject).toBe(1);
         |                          ^
      42 |   });
      43 | 
      44 |   test('should resolve when the dice settles successfully', () => {

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:41:26)

  ● rollDice › should resolve when the dice settles successfully

    TypeError: callback is not a function

      30 |     if (roll === randomRollsToDo) {
      31 |       // TODO replace "success" callback
    > 32 |       callback(null, value);
         |       ^
      33 |     }
      34 | 
      35 |     // Schedule the next roll todo until no more rolls to do

      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDice.js:32:7)
      at cb (3-UsingAPIs/Week1/homework/ex3-rollDice.js:37:24)
      at 3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:52:35
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDice.js:37:7)
      at cb (3-UsingAPIs/Week1/homework/ex3-rollDice.js:37:24)
      at 3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:52:35
      at rollOnce (3-UsingAPIs/Week1/homework/ex3-rollDice.js:37:7)
      at rollDice (3-UsingAPIs/Week1/homework/ex3-rollDice.js:42:3)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:54:21)

  ● rollDice › should resolve when the dice settles successfully

    expect.assertions(2)

    Expected two assertions to be called but received zero assertion calls.

      44 |   test('should resolve when the dice settles successfully', () => {
      45 |     if (!exported) return;
    > 46 |     expect.assertions(2);
         |            ^
      47 | 
      48 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      49 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:46:12)

  ● rollDice › should reject with an Error when the dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      67 |   test('should reject with an Error when the dice rolls off the table', async () => {
      68 |     if (!exported) return;
    > 69 |     expect.assertions(2);
         |            ^
      70 | 
      71 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      72 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex3-rollDice.test.js:69:12)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        2.584 s
Ran all test suites matching /ex3-rollDice.test.js/i.

2021-08-28 08:51:19 info: ----------------------------------------
2021-08-28 08:51:19 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-28 08:51:19 info: ----------------------------------------
2021-08-28 08:51:23 info: All unit tests passed.
2021-08-28 08:51:25 error: *** ESLint Report ***

ex3-rollDice.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-30 03:20:29 info: --------------------------------------------
2021-08-30 03:20:29 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 03:20:29 info: --------------------------------------------
2021-08-30 03:20:38 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:31:31


2021-08-30 03:20:40 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  28:9  error  'dices' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-30 03:21:37 info: --------------------------------------------
2021-08-30 03:21:37 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 03:21:37 info: --------------------------------------------
2021-08-30 03:21:45 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:31:31


2021-08-30 03:21:47 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  28:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 1 problem (0 errors, 1 warning)


2021-08-30 03:36:26 info: --------------------------------------------
2021-08-30 03:36:26 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 03:36:26 info: --------------------------------------------
2021-08-30 03:36:30 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:31:31


2021-08-30 03:36:32 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  28:9  error  'dices' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-30 03:37:05 info: --------------------------------------------
2021-08-30 03:37:05 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 03:37:05 info: --------------------------------------------
2021-08-30 03:37:09 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:31:31


2021-08-30 03:39:06 info: --------------------------------------------
2021-08-30 03:39:06 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 03:39:06 info: --------------------------------------------
2021-08-30 03:39:10 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:31:31


2021-08-30 03:45:47 info: ----------------------------------------------
2021-08-30 03:45:47 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 03:45:47 info: ----------------------------------------------
2021-08-30 03:45:52 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    √ should resolve when all dices settle successfully (2 ms)
    × should reject with an Error when a dice rolls off the table (3 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        2.343 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 03:47:26 info: ----------------------------------------------
2021-08-30 03:47:26 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 03:47:26 info: ----------------------------------------------
2021-08-30 03:47:30 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (2 ms)
    √ should resolve when all dices settle successfully (3 ms)
    × should reject with an Error when a dice rolls off the table (2 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        2.258 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:08:37 info: ----------------------------------------------
2021-08-30 09:08:37 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:08:37 info: ----------------------------------------------
2021-08-30 09:08:45 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    √ should resolve when all dices settle successfully (4 ms)
    × should reject with an Error when a dice rolls off the table (3 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        4.069 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:10:19 info: ----------------------------------------------
2021-08-30 09:10:19 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:10:19 info: ----------------------------------------------
2021-08-30 09:10:26 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    √ should resolve when all dices settle successfully (3 ms)
    × should reject with an Error when a dice rolls off the table (4 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        3.475 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:13:51 info: ----------------------------------------------
2021-08-30 09:13:51 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:13:51 info: ----------------------------------------------
2021-08-30 09:13:59 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    √ should resolve when all dices settle successfully (4 ms)
    × should reject with an Error when a dice rolls off the table (3 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        4.079 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:28:38 info: ----------------------------------------------
2021-08-30 09:28:38 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:28:38 info: ----------------------------------------------
2021-08-30 09:28:44 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    √ should resolve when all dices settle successfully (3 ms)
    × should reject with an Error when a dice rolls off the table (4 ms)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        3.762 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:28:47 error: *** ESLint Report ***

ex5-pokerDiceChain.js
  36:12  error  'value' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-30 09:37:11 info: ----------------------------------------------
2021-08-30 09:37:11 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:37:11 info: ----------------------------------------------
2021-08-30 09:37:18 error: *** Unit Test Error Report ***

Command failed: npx jest ex5-pokerDiceChain.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js
  ex5-pokerDiceChain
    √ should exist and be executable (3 ms)
    × should resolve when all dices settle successfully (7 ms)
    × should reject with an Error when a dice rolls off the table (4 ms)

  ● ex5-pokerDiceChain › should resolve when all dices settle successfully

    expect(received).resolves.toBeDefined()

    Received: undefined

      26 |     const promise = rollTheDices();
      27 |     expect(promise).toBeInstanceOf(Promise);
    > 28 |     const assertionPromise = expect(promise).resolves.toBeDefined();
         |                                                       ^
      29 | 
      30 |     promise.finally(() => {
      31 |       setTimeoutSpy.mockRestore();

      at Object.toBeDefined (node_modules/expect/build/index.js:198:20)
      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:28:55)

  ● ex5-pokerDiceChain › should reject with an Error when a dice rolls off the table

    expect.assertions(2)

    Expected two assertions to be called but received one assertion call.

      39 |   test('should reject with an Error when a dice rolls off the table', async () => {
      40 |     if (!exported) return;
    > 41 |     expect.assertions(2);
         |            ^
      42 | 
      43 |     const logSpy = jest.spyOn(console, 'log').mockImplementation();
      44 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex5-pokerDiceChain.test.js:41:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        3.926 s
Ran all test suites matching /ex5-pokerDiceChain.test.js/i.

2021-08-30 09:39:22 info: ----------------------------------------------
2021-08-30 09:39:22 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-30 09:39:22 info: ----------------------------------------------
2021-08-30 09:39:29 info: All unit tests passed.
2021-08-30 09:39:34 info: All steps were completed successfully
2021-08-30 09:51:00 info: --------------------------------------------
2021-08-30 09:51:00 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 09:51:00 info: --------------------------------------------
2021-08-30 09:51:07 error: *** Unit Test Error Report ***

  console.log
    Rejected! Dice 1 rolled off the table.

      at 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js:32:31


2021-08-30 09:51:09 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  27:9  error  'dices' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-30 10:04:27 info: --------------------------------------------
2021-08-30 10:04:27 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-30 10:04:27 info: --------------------------------------------
2021-08-30 10:04:34 info: All unit tests passed.
2021-08-30 10:04:37 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  27:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 1 problem (0 errors, 1 warning)


2021-08-31 10:28:13 info: --------------------------------------------
2021-08-31 10:28:13 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-31 10:28:13 info: --------------------------------------------
2021-08-31 10:28:19 info: All unit tests passed.
2021-08-31 10:28:20 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  27:3  warning  Remove commented-out code  hyf/no-commented-out-code

✖ 1 problem (0 errors, 1 warning)


2021-08-31 10:28:23 error: *** Spell Checker Report ***

ex4-pokerDiceAll.js:36:25 - Unknown word (Obada's)

2021-08-31 10:28:35 info: ----------------------------------------------
2021-08-31 10:28:35 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-31 10:28:35 info: ----------------------------------------------
2021-08-31 10:28:40 info: All unit tests passed.
2021-08-31 10:28:43 info: All steps were completed successfully
2021-08-31 11:30:47 info: ---------------------------------------
2021-08-31 11:30:47 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-31 11:30:47 info: ---------------------------------------
2021-08-31 11:30:54 info: All unit tests passed.
2021-08-31 11:30:58 info: All steps were completed successfully
2021-08-31 11:31:14 info: -------------------------------------------------
2021-08-31 11:31:14 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-31 11:31:14 info: -------------------------------------------------
2021-08-31 11:31:19 error: *** Unit Test Error Report ***

  console.log
    This is a double digit number!

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:26:30

  console.log
    Expected a double digit number but got 5

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:31:29

  console.log
    Expected a double digit number but got 123

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:35:29


2021-08-31 11:32:32 info: -------------------------------------------------
2021-08-31 11:32:32 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-31 11:32:32 info: -------------------------------------------------
2021-08-31 11:32:37 error: *** Unit Test Error Report ***

  console.log
    This is a double digit number!

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:27:30

  console.log
    Expected a double digit number but got 5

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:32:29

  console.log
    Expected a double digit number but got 123

      at 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js:36:29


2021-08-31 11:33:39 info: -------------------------------------------------
2021-08-31 11:33:39 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-31 11:33:39 info: -------------------------------------------------
2021-08-31 11:33:43 info: All unit tests passed.
2021-08-31 11:33:46 info: All steps were completed successfully
2021-08-31 11:34:24 info: ----------------------------------------
2021-08-31 11:34:24 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-31 11:34:24 info: ----------------------------------------
2021-08-31 11:34:28 info: All unit tests passed.
2021-08-31 11:34:31 info: All steps were completed successfully
2021-08-31 11:34:57 info: --------------------------------------------
2021-08-31 11:34:57 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-31 11:34:57 info: --------------------------------------------
2021-08-31 11:35:01 info: All unit tests passed.
2021-08-31 11:35:03 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  29:9  warning  Results from `map` are unused. Replace `map` with `forEach`  no-restricted-syntax
  29:9  error    Results from `map` are unused. Replace `map` with `forEach`  hyf/use-map-result

✖ 2 problems (1 error, 1 warning)


2021-08-31 11:35:05 error: *** Spell Checker Report ***

ex4-pokerDiceAll.js:35:21 - Unknown word (Obada's)

2021-08-31 11:37:19 info: ----------------------------------------------
2021-08-31 11:37:19 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-31 11:37:19 info: ----------------------------------------------
2021-08-31 11:37:23 info: All unit tests passed.
2021-08-31 11:37:27 info: All steps were completed successfully
2021-08-31 11:44:35 info: ----------------------------------------------
2021-08-31 11:44:35 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-31 11:44:35 info: ----------------------------------------------
2021-08-31 11:44:38 info: All unit tests passed.
2021-08-31 11:44:42 info: All steps were completed successfully
2021-09-15 10:47:13 info: -------------------------------------------------
2021-09-15 10:47:13 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-09-15 10:47:13 info: -------------------------------------------------
2021-09-15 10:47:21 info: All unit tests passed.
2021-09-15 10:47:26 info: All steps were completed successfully
